FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o unifi-cloudflare-ddns-go main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/unifi-cloudflare-ddns-go .

ENTRYPOINT [ "./unifi-cloudflare-ddns-go" ]