FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the binary with CGO disabled to ensure it's statically linked
RUN CGO_ENABLED=0 GOOS=linux go build -o unifi-cloudflare-ddns-go main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/unifi-cloudflare-ddns-go .

ENTRYPOINT [ "/root/unifi-cloudflare-ddns-go" ]